language: node_js

node_js:
  - "14"

sudo: required

services:
  - docker


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: "$SECRETACCESSKEY"
  region: "us-west-2"  
  app: "node-docker"
  env: "Nodedocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-719156614080"
  on:
    branch: master

after_deploy:
  - echo "done deploying!"
