language: node_js

node_js:
  - "12"

sudo: required

services:
  - docker

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-west-2
  app: "node-docker"
  env: "Nodedocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-719156614080"
  bucket_path: node-docker-example
  on:
    branch: master

after_deploy:
  - echo "done deploying!"
