language: node_js

node_js:
  - "12"

#install: skip

#script: skip

sudo: required

services:
  - docker


before_install:
  - docker build -t node-docker/node-docker-example .

#script:
#  - docker run node-docker npm run test -- --coverage

after_success:
  #log in to docker
  echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to Docker Hub
  docker push yyosefi/node-docker

#jobs:
#  include:
#    - stage: test
#      script:
#        - npm test
#    - stage: docker-build
#      script: 
#        - docker build -t node-docker/node-docker-example .
#    - stage: deploy
      #script: skip

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-west-2  
  app: "node-docker"
  env: "Nodedocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-719156614080"
  bucket_path: node-docker-example
  on:
    branch: master

after_deploy:
  - echo "done deploying!"
